title: "TSSR Notes"
remote_theme: pmarsceill/just-the-docs

# Recherche full-text activée
search_enabled: true

# Thème sombre toggle
color_scheme: dark

# Arborescence dans la sidebar
nav_sort: case_insensitive

# Fichier d'accueil
home_page: index.md


# Bisous à ceux qui look le code source ;)
